name = "mcp-oauth-proxy"
main = "src/index.ts"
compatibility_date = "2025-01-01"

# Deploy to a custom domain by adding a route:
# [[routes]]
# pattern = "mcp.zephan.space/*"
# zone_name = "zephan.space"


[[kv_namespaces]]
binding = "KV"
id = "11a14ffe7aa2455e92fa2266530fb85e"